version: "3.9"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: skytouch-brian
      POSTGRES_PASSWORD: skytouch-brian
      POSTGRES_DB: skytouch
    ports:
      - "5432:5432"
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"