version: "3.9"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: skytouch-brian
      POSTGRES_PASSWORD: skytouch-brian
      POSTGRES_DB: skytouch
    ports:
      - "5431:5432"
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5671:5672"
      - "15671:15672"

networks:
  default:
    driver: bridge

